output:
  udmx:
    type: udmx
    parameters:
      device: 0
  light:
    type: wemo
    parameters:
      username: test123@gmail.com
      password: laded
      id: random
  vlc:
    type: vlc
    parameters:
      ip: 192.168.5.3
      username: test123
      password: 1234
input:
  wyzecam:
    type: wyze
    parameters:
      username: ...
      password: ...
      device: ...
sequence:
  - event: input
    device: wyze
    trigger: motion 
  - event: time
    steps:
    - ts: "00:00:00.000"
      device: vlc
      parameters:
        - action: start
